# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://d3y0lbg7abxmbuoi.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/po6bi80ttuwjm6r1
    username: hj7hzxm5u7v1kv1p
    password: kx8rwdi82s56uwag
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

