# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://kwefz2gf50vislgn:mlomx5egvv93tun0@r6ze0q02l4me77k3.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/xjztkrppu2znofkx
    username: kwefz2gf50vislgn
    password: mlomx5egvv93tun0
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

